name: stale repo archiver API

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOK }}  
          script: |
            const script = require('./\.github/workflows/repoArch.js')
            script({github, context})
