name: stale repo archiver API

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./\.github/workflows/repoArch.js')
            script({github, context})
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
         title: Stale repository report
         content-filepath: ./stale_repos.md
         assignees: <YOUR_GITHUB_HANDLE_HERE>
         token: ${{ secrets.GITHUB_TOKEN }}      
