name: stale repo identifier

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Run stale_repos tool
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.TOK }}
        ORGANIZATION: ""
        EXEMPT_TOPICS: "keep,template"
        INACTIVE_DAYS: 0

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        assignees: "shmishra99"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive Repo   
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
          script: |
            return github.rest.repos.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            archive: true
               });

            
